### ISSUE TITLE
[Bug] B30 table displays the opposite side of scores_best table

### ISSUE THREAD

**Issue by JustVldKsh** [ArcaeaOffline/client-pyside6#11]
While looking around the program for things to report about, stumbled upon that oddity

And after some poking around, I've found out that `ScoreBest.potential` in https://github.com/ArcaeaOffline/client-pyside6/blob/master/ui/extends/shared/models/tables/b30.py#L42 is missing `.desc()` attribute that also was present before https://github.com/ArcaeaOffline/client-pyside6/commit/d460e935b4926d0e9bbdd92876bb75253b3e9b6d

Edit: should be a one-minute fix that shouldn't cause any issues

**Comment by 283375** [comment]
💀
