### ISSUE TITLE
Unable to select Eternal difficulty charts in chart info editor's "No chart data" list

### ISSUE THREAD

**Issue by JustVldKsh** [ArcaeaOffline/client-pyside6#6]
Basically the title
It also resets the difficulty choice on click (unless Eternal is already selected) when switching from another chart, but in that case song selection changes to the selected one 

https://github.com/ArcaeaOffline/client-pyside6/assets/49518100/4bc8020b-3420-429f-b82c-b8e352bf5e2b

**Comment by 283375** [comment]
It appears that the hard coded rating class range (0~3) prevents eternal (4) to be selected, should be fixed at the linked pr.

**Comment by JustVldKsh** [comment]
Yeah, seems to work properly now
