### ISSUE TITLE
[Feature Request] Ability to choose where the date of the score is taken from during OCR

### ISSUE THREAD

**Issue by JustVldKsh** [ArcaeaOffline/client-pyside6#9]
Would be nice to have the ability to pick between file creation and modification time, especially considering how file creation date works on common Linux filesystems (idk about other operating systems). On ext4 and others, creation date is when the file was created on the filesystem and cannot be edited, unlike modification time that is changed only on data modification and is generally accurate in my case (and even if it wasn't, it is possible to fix with a script)

Probably kind of a niche thing, but would save a good amount of time for someone who cares about timestamps and stuff, like me

**Comment by 283375** [comment]
Do you mean those file choosers? I'm using the Qt [QFileDialog](https://doc.qt.io/qt-6/qfiledialog.html) for `FileSelector`, so I think it should open the system's native file dialog, and there should be some options to toggle the columns you like? Or if this isn't the case?

**Comment by JustVldKsh** [comment]
Yeah, I'm about where the OCR itself pulls the date/time from and adds to the scores, not file dialog

**Comment by 283375** [comment]
I'm planning to add a new settings entry for this, but I can't really understand what I wrote before... so I'm temporarily delaying this issue until I'm fully available

However, you may change this function (Specifically L71):

https://github.com/ArcaeaOffline/client-pyside6/blob/d5895fe2306862f69796328fb6943f5ba7f13653/ui/extends/tabs/tabOcr/tabOcr_Device.py#L62-L73

Like this:

```diff
- datetime = QFileInfo(imagePath).birthTime()
+ datetime = QFileInfo(imagePath).lastModified()
```

Then the date should be extracted from the file modification date. You may refer to <https://doc.qt.io/qt-6.5/qfileinfo.html> for more choices.

**Comment by JustVldKsh** [comment]
Thanks for telling where to look for a quick temporary fix/edit

Will note it down and probably process my scores tomorrow, will report back if any more issues arise along the way

**Comment by 283375** [comment]
The new `v0.3.9` adds a settings button in the OCR tab. I've tested it on Windows, and you may check if it works.

Also I've noticed the packaging library ([nuitka](https://github.com/Nuitka/Nuitka)) has a linux option now, and I've [tried building it](https://github.com/ArcaeaOffline/client-pyside6/actions/runs/9585134180) using GitHub Actions. The output is a single `.bin` file, I'm not sure if it's an "executable" or whatever😕Could you give it a try?

**Comment by JustVldKsh** [comment]
Sure, will try tomorrow!

**Comment by JustVldKsh** [comment]
LGTM! A simple `chmod +x` (or even just a single confirmation that I do want to run it in the desktop I use) and it works! I think all the issues I opened can be closed after the actual release
